"""

PR Handler - Manages the multi-step PR setup phase.

Flow:  ask_branch -> ask_title -> show_files -> confirm -> execute

At each step the user can:
  - answer the question
  - say add resource / I want another resource  -> handled by generator_agent
  - say cancel / skip pr                        -> abort PR flow
"""
import re
import time
import logging
from typing import Optional

from app.agents.session_state import SessionState, AgentState, extract_branch_name
from app.agents.prompts import PR_SETUP_PROMPT, SYSTEM_PROMPT
from app.services.scm_adapter import (
    create_pr_for_resource,
    create_pr_for_batch,
    check_fork_status,
    get_upstream_branches,
)
from app.services.llm_client import llm_client
from app.config import settings

logger = logging.getLogger(__name__)


# ================================================================
# HELPERS
# ================================================================


def build_response(
    message,
    resource_type=None,
    resource_status=None,
    generated_yaml=None,
    needs_confirmation=False,
    pr_url=None,
    _extracted_fields=None,
):
    resp = {
        "message": message,
        "resource_type": resource_type,
        "resource_status": resource_status,
        "generated_yaml": generated_yaml,
        "needs_confirmation": needs_confirmation,
        "pr_url": pr_url,
    }
    if _extracted_fields is not None:
        resp["_extracted_fields"] = _extracted_fields
    return resp


async def _save_pr_record(
    session,
    pr_url,
    branch_name,
    target_branch,
    title,
    resource_types,
    resource_count=1,
):
    try:
        from app.models.database import async_session_factory
        from app.models.schemas import PRRecord

        pr_number = None
        match = re.search(r"/pull/(\d+)", pr_url)
        if match:
            pr_number = int(match.group(1))

        repo_full_name = (
            f"{settings.github_upstream_owner}/{settings.github_upstream_repo}"
        )

        async with async_session_factory() as db:
            record = PRRecord(
                session_id=session.session_id,
                github_username=session.github_username or "unknown",
                pr_url=pr_url,
                pr_number=pr_number,
                repo_full_name=repo_full_name,
                branch_name=branch_name,
                target_branch=target_branch or settings.github_upstream_branch,
                resource_types=resource_types,
                resource_count=resource_count,
                title=title,
            )
            db.add(record)
            await db.commit()
            logger.info(f"Saved PR record: {pr_url}")
    except Exception as e:
        logger.error(f"Failed to save PR record: {e}")


def _generate_smart_title(agent):
    rtype = (agent.resource_type or "unknown").upper()
    fields = agent.collected_fields or {}
    intake_id = fields.get("intake_id", "unknown")
    resource_name = (
        fields.get("bucket_name")
        or fields.get("database_name")
        or fields.get("role_name")
        or "unknown"
    )
    return f"[CONFIG] {rtype} - {intake_id} - {resource_name}"


def _generate_smart_body(agent):
    rtype = (agent.resource_type or "unknown").upper()
    fields = agent.collected_fields or {}
    intake_id = fields.get("intake_id", "unknown")
    resource_name = (
        fields.get("bucket_name")
        or fields.get("database_name")
        or fields.get("role_name")
        or "unknown"
    )
    yaml_content = agent.generated_yaml or "(no YAML)"
    return (
        f"## Infrastructure Configuration\n\n"
        f"**Resource Type:** {rtype}\n"
        f"**Intake ID:** {intake_id}\n"
        f"**Resource Name:** {resource_name}\n\n"
        f"```yaml\n{yaml_content}\n```\n\n"
        f"---\n"
        f"_This PR was automatically generated by PR Chatbot._"
    )


def _resolve_file_paths(batch):
    from app.services.path_resolver import resolve_file_path

    paths = []
    for entry in batch:
        try:
            path = resolve_file_path(
                entry["resource_type"], entry.get("fields", {})
            )
        except Exception:
            name = entry.get("resource_name") or entry.get("intake_id", "unknown")
            path = f"configs/{entry['resource_type']}/{entry.get('intake_id', '')}-{name}.yaml"
        paths.append(path)
    return paths


def _is_skip(msg):
    return msg in {"skip", "skip pr", "no pr", "save only", "3"}


def _is_cancel(msg):
    return msg in {"cancel", "abort", "stop", "quit"}


def _wants_new_resource(msg):
    triggers = [
        "add another",
        "add resource",
        "add a resource",
        "new resource",
        "i want another",
        "create another",
        "one more",
        "add one more",
        "i want to create",
        "i need another",
    ]
    return any(t in msg for t in triggers)


# ================================================================
# ENTRY POINT - called when user says create PR
# ================================================================


async def present_pr_setup(session, agent):
    batch = session.batch
    is_batch = agent.resource_type == "batch"

    if is_batch:
        from collections import Counter

        count = len(batch)
        type_counts = Counter(e["resource_type"].upper() for e in batch)
        type_summary = ", ".join(f"{v} {k}" for k, v in type_counts.items())
        first_intake = batch[0]["intake_id"]
        default_branch = f"config/batch-{first_intake}-{int(time.time())}"
        agent.pr_title = agent.pr_title or f"[CONFIG] Batch - {type_summary}"
        body_lines = [
            f"## Infrastructure Configuration Batch ({count} resources)\n"
        ]
        for i, entry in enumerate(batch, 1):
            body_lines.append(
                f"### {i}. {entry['resource_type'].upper()} - {entry['resource_name']}"
            )
            body_lines.append(f"**Intake ID:** {entry['intake_id']}")
            body_lines.append(f"```yaml\n{entry['yaml']}\n```\n")
        body_lines.append(
            "---\n_This PR was automatically generated by PR Chatbot._"
        )
        agent.pr_body = agent.pr_body or "\n".join(body_lines)
    else:
        fields = agent.collected_fields or {}
        intake_id = fields.get("intake_id", "unknown")
        default_branch = (
            f"config/{agent.resource_type}-{intake_id}-{int(time.time())}"
        )
        if not agent.pr_title:
            agent.pr_title = _generate_smart_title(agent)
        if not agent.pr_body:
            agent.pr_body = _generate_smart_body(agent)

    agent.pr_branch_name = default_branch

    try:
        fork_info = await check_fork_status(session.github_token)
        agent.fork_exists = fork_info.get("exists", False)
        agent.fork_full_name = fork_info.get("fork_full_name")
    except Exception:
        agent.fork_exists = False

    try:
        branches = await get_upstream_branches(session.github_token)
        agent.available_branches = branches
    except Exception:
        branches = [settings.github_upstream_branch]
        agent.available_branches = branches

    agent.pr_target_branch = settings.github_upstream_branch
    agent.pr_sub_phase = "ask_branch"
    agent.phase = "pr_setup"

    branch_list = "\n".join(f"  - `{b}`" for b in branches[:10])
    upstream = f"{settings.github_upstream_owner}/{settings.github_upstream_repo}"

    msg = (
        f"**PR Setup**\n\n"
        f"Which branch should this PR target on `{upstream}`?\n"
        f"Available branches:\n{branch_list}\n\n"
        f"Type a branch name, or just say **confirm** to use the default"
        f" (`{agent.pr_target_branch}`).\n"
        f"You can also say **skip pr** or **cancel**."
    )

    return build_response(
        msg, resource_type=agent.resource_type, resource_status="pr_setup"
    )


# ================================================================
# MAIN ROUTER
# ================================================================


async def handle_pr_setup(session, user_message):
    agent = session.current_agent
    msg_lower = user_message.strip().lower()

    logger.info("[PR] handle_pr_setup: sub_phase=%s, user_msg=%.80s",
                getattr(agent, 'pr_sub_phase', 'ask_branch'), msg_lower[:80])

    if _is_skip(msg_lower):
        return _handle_skip(session, agent)

    if _is_cancel(msg_lower):
        return _handle_skip(session, agent)

    if _wants_new_resource(msg_lower):
        return _handle_pause_for_new_resource(session, agent)

    sub = getattr(agent, "pr_sub_phase", "ask_branch")

    if sub == "ask_branch":
        return _handle_ask_branch(session, agent, user_message)
    elif sub == "ask_title":
        return await _handle_ask_title(session, agent, user_message)
    elif sub == "show_files":
        return _handle_show_files(session, agent, user_message)
    elif sub == "confirm":
        return await _handle_confirm(session, agent, user_message)
    else:
        return await _handle_llm_fallback(session, agent, user_message)


# ================================================================
# SUB-PHASE HANDLERS
# ================================================================


def _handle_ask_branch(session, agent, user_message):
    msg_lower = user_message.strip().lower()
    confirm_words = {"confirm", "yes", "ok", "default", "y", "proceed", "1"}

    if msg_lower not in confirm_words:
        branch = user_message.strip().strip("`'\"")
        available = agent.available_branches or []
        if available and branch not in available:
            branch_list = "\n".join(f"  - `{b}`" for b in available[:10])
            return build_response(
                f"Branch `{branch}` doesn't exist on the upstream repo.\n\n"
                f"Available branches:\n{branch_list}\n\n"
                f"Pick one of these, or **confirm** to use"
                f" `{agent.pr_target_branch}`.",
                resource_type=agent.resource_type,
                resource_status="pr_setup",
            )
        agent.pr_target_branch = branch

    agent.pr_sub_phase = "ask_title"

    suggested_title = agent.pr_title or "(auto-generated)"
    suggested_body = agent.pr_body or "(auto-generated)"
    body_preview = suggested_body[:300]
    if len(suggested_body) > 300:
        body_preview += "\n..."

    msg = (
        f"Target branch: `{agent.pr_target_branch}`\n\n"
        f"**Suggested PR title:**\n> {suggested_title}\n\n"
        f"**Suggested PR body:**\n```\n{body_preview}\n```\n\n"
        f"Would you like to **confirm** these, or provide your own?\n"
        f"Examples:\n"
        f"  - `confirm` - use the suggested title and body\n"
        f"  - `title: My Custom Title` - change only the title\n"
        f"  - `body: My custom description` - change only the body\n"
        f"  - provide both: `title: X` and `body: Y`"
    )
    return build_response(
        msg, resource_type=agent.resource_type, resource_status="pr_setup"
    )


async def _handle_ask_title(session, agent, user_message):
    msg_lower = user_message.strip().lower()
    confirm_words = {
        "confirm", "yes", "ok", "y", "looks good", "proceed", "1", "lgtm"
    }

    if msg_lower not in confirm_words:
        title_match = re.search(
            r"title\s*[:=]\s*(.+?)(?:\n|body\s*[:=]|$)",
            user_message,
            re.IGNORECASE,
        )
        body_match = re.search(
            r"body\s*[:=]\s*(.+)",
            user_message,
            re.IGNORECASE | re.DOTALL,
        )

        if title_match:
            agent.pr_title = title_match.group(1).strip().strip("`'\"")
        elif not body_match:
            return await _handle_llm_fallback(session, agent, user_message)

        if body_match:
            agent.pr_body = body_match.group(1).strip().strip("`'\"")

    agent.pr_sub_phase = "show_files"
    return _present_files(session, agent)


def _present_files(session, agent):
    is_batch = agent.resource_type == "batch"
    batch = session.batch

    if is_batch and batch:
        paths = _resolve_file_paths(batch)
        file_lines = "\n".join(f"  {i}. `{p}`" for i, p in enumerate(paths, 1))
    else:
        try:
            from app.services.path_resolver import resolve_file_path

            path = resolve_file_path(
                agent.resource_type, agent.collected_fields or {}
            )
        except Exception:
            path = f"configs/{agent.resource_type}/unknown.yaml"
        file_lines = f"  1. `{path}`"

    msg = (
        f"**Files to be created:**\n{file_lines}\n\n"
        f"Does this look correct?\n"
        f"  - **confirm** - proceed to final summary\n"
        f"  - Tell me what is wrong and I will adjust"
    )
    return build_response(
        msg, resource_type=agent.resource_type, resource_status="pr_setup"
    )


def _handle_show_files(session, agent, user_message):
    msg_lower = user_message.strip().lower()
    confirm_words = {
        "confirm", "yes", "ok", "y", "looks good", "proceed",
        "correct", "1", "lgtm", "good",
    }

    if msg_lower in confirm_words:
        agent.pr_sub_phase = "confirm"
        return _present_final_summary(session, agent)

    return build_response(
        "File paths are automatically determined from your resource configuration"
        " (account ID to folder mapping). To change a file path, you would need"
        " to edit the resource's `aws_account_id` or `bucket_name`.\n\n"
        "Would you like to **confirm** these paths, or **cancel** to go back?",
        resource_type=agent.resource_type,
        resource_status="pr_setup",
    )


def _present_final_summary(session, agent):
    is_batch = agent.resource_type == "batch"
    batch = session.batch
    upstream = f"{settings.github_upstream_owner}/{settings.github_upstream_repo}"

    if agent.fork_exists:
        fork_line = f"`{agent.fork_full_name}` (exists)"
    else:
        fork_line = (
            f"`{session.github_username or 'you'}"
            f"/{settings.github_upstream_repo}` (will be created)"
        )

    if is_batch and batch:
        paths = _resolve_file_paths(batch)
        file_lines = "\n".join(f"  - `{p}`" for p in paths)
        resource_count = len(batch)
    else:
        try:
            from app.services.path_resolver import resolve_file_path

            path = resolve_file_path(
                agent.resource_type, agent.collected_fields or {}
            )
        except Exception:
            path = f"configs/{agent.resource_type}/unknown.yaml"
        file_lines = f"  - `{path}`"
        resource_count = 1

    msg = (
        f"**Final PR Summary:**\n\n"
        f"| | |\n"
        f"|---|---|\n"
        f"| **Fork** | {fork_line} |\n"
        f"| **Branch** | `{agent.pr_branch_name}` |\n"
        f"| **Target** | `{upstream}:{agent.pr_target_branch}` |\n"
        f"| **Title** | {agent.pr_title} |\n"
        f"| **Files** | {resource_count} file(s) |\n\n"
        f"Files:\n{file_lines}\n\n"
        f"Shall I go ahead and **create the PR**?\n"
        f"Type **yes** to create, or **cancel** to abort."
    )
    return build_response(
        msg, resource_type=agent.resource_type, resource_status="pr_setup"
    )


async def _handle_confirm(session, agent, user_message):
    msg_lower = user_message.strip().lower()
    confirm_words = {
        "yes", "confirm", "ok", "y", "go ahead", "create", "create pr",
        "proceed", "do it", "1", "create the pr", "go", "sure",
    }

    if msg_lower in confirm_words:
        if agent.resource_type == "batch":
            return await execute_batch_pr_creation(session, agent)
        return await execute_pr_creation(session, agent)

    if "back" in msg_lower or "change" in msg_lower or "edit" in msg_lower:
        agent.pr_sub_phase = "ask_title"
        return build_response(
            "Sure! What would you like to change?\n"
            "  - `title: New Title` - change the PR title\n"
            "  - `body: New Body` - change the PR description\n"
            "  - Say **confirm** when done",
            resource_type=agent.resource_type,
            resource_status="pr_setup",
        )

    return build_response(
        "Please type **yes** to create the PR, **cancel** to abort,"
        " or **back** to make changes.",
        resource_type=agent.resource_type,
        resource_status="pr_setup",
    )


# ================================================================
# SKIP / PAUSE / LLM FALLBACK
# ================================================================


def _handle_skip(session, agent):
    agent.phase = "done"
    rtype = (agent.resource_type or "unknown").upper()

    if agent.resource_type == "batch":
        for entry in session.batch:
            session.completed_resources.append(entry)
        session.clear_batch()
        session.current_agent = None
        count = len(session.completed_resources)
        return build_response(
            f"**{count} configurations saved!** (No PR created)\n\n"
            f"Would you like to create another resource, or are we done?",
            resource_status="confirmed",
        )

    session.complete_current_resource()
    return build_response(
        f"**{rtype} configuration saved!** (No PR created)\n\n"
        f"Would you like to create another resource, or are we done?",
        resource_type=agent.resource_type,
        resource_status="confirmed",
        generated_yaml=agent.generated_yaml,
    )


def _handle_pause_for_new_resource(session, agent):
    session.paused_pr_state = {
        "pr_sub_phase": getattr(agent, "pr_sub_phase", "ask_branch"),
        "pr_branch_name": agent.pr_branch_name,
        "pr_title": agent.pr_title,
        "pr_body": agent.pr_body,
        "pr_target_branch": agent.pr_target_branch,
        "available_branches": agent.available_branches,
        "fork_exists": agent.fork_exists,
        "fork_full_name": agent.fork_full_name,
        "resource_type": agent.resource_type,
        "collected_fields": (agent.collected_fields or {}).copy(),
        "generated_yaml": agent.generated_yaml,
    }

    session.current_agent = None

    batch_count = len(session.batch)
    return build_response(
        f"PR setup paused. Your batch"
        f" ({batch_count} resource{'s' if batch_count != 1 else ''})"
        f" is safe.\n\nGo ahead - what resource would you like to add?",
        resource_status="idle",
    )


async def _handle_llm_fallback(session, agent, user_message):
    upstream = f"{settings.github_upstream_owner}/{settings.github_upstream_repo}"

    if agent.fork_exists:
        fork_info = f"`{agent.fork_full_name}` (exists)"
    else:
        fork_info = (
            f"`{session.github_username or 'you'}"
            f"/{settings.github_upstream_repo}` (will be created)"
        )

    prompt = PR_SETUP_PROMPT.format(
        resource_type=agent.resource_type or "unknown",
        branch_name=agent.pr_branch_name or "N/A",
        fork_info=fork_info,
        upstream_info=(
            f"{upstream}:"
            f"{agent.pr_target_branch or settings.github_upstream_branch}"
        ),
        target_branch=agent.pr_target_branch or settings.github_upstream_branch,
        available_branches=", ".join(
            agent.available_branches or [settings.github_upstream_branch]
        ),
        pr_title=agent.pr_title or "(auto-generated)",
        yaml_content=agent.generated_yaml or "(no YAML generated yet)",
        user_message=user_message,
    )

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": prompt},
    ]

    try:
        result = await llm_client.extract_json(messages)
    except Exception as e:
        logger.error(f"PR setup LLM fallback failed: {e}")
        return build_response(
            "I had trouble understanding that. You can:\n"
            "  - **confirm** / **yes** - proceed\n"
            "  - **cancel** / **skip pr** - abort\n"
            "  - Type `title: X` to change the title",
            resource_type=agent.resource_type,
            resource_status="pr_setup",
        )

    action = result.get("action", "question")
    message = result.get("message", "")
    proceed_after = result.get("proceed_after", False)

    if action == "edit_config":
        extracted_fields = result.get("extracted_fields", {})
        if extracted_fields and isinstance(extracted_fields, dict):
            return build_response(
                message or "Updating your configuration...",
                resource_type=agent.resource_type,
                resource_status="edit_config_requested",
                generated_yaml=agent.generated_yaml,
                _extracted_fields=extracted_fields,
            )
        return build_response(
            "Which field would you like to change?",
            resource_type=agent.resource_type,
            resource_status="pr_setup",
        )

    if action == "show_yaml":
        yaml_display = agent.generated_yaml or "(No YAML generated yet)"
        return build_response(
            f"```yaml\n{yaml_display}\n```\n\n"
            f"You can **confirm** to continue, or **edit** fields.",
            resource_type=agent.resource_type,
            resource_status="pr_setup",
            generated_yaml=agent.generated_yaml,
        )

    if action == "change_settings":
        changes = []
        new_branch = result.get("branch_name")
        if new_branch:
            agent.pr_branch_name = new_branch.strip().strip("`'\"")
            changes.append(f"Branch: `{agent.pr_branch_name}`")

        new_target = result.get("target_branch")
        if new_target:
            new_target = new_target.strip().strip("`'\"")
            available = agent.available_branches or []
            if available and new_target not in available:
                branch_list = ", ".join(f"`{b}`" for b in available)
                return build_response(
                    f"Branch `{new_target}` doesn't exist.\n"
                    f"Available: {branch_list}",
                    resource_type=agent.resource_type,
                    resource_status="pr_setup",
                )
            agent.pr_target_branch = new_target
            changes.append(f"Target: `{new_target}`")

        new_title = result.get("pr_title")
        if new_title:
            agent.pr_title = new_title.strip()
            changes.append(f"Title: **{agent.pr_title}**")

        new_body = result.get("pr_body")
        if new_body:
            agent.pr_body = new_body.strip()
            changes.append("Description updated")

        if proceed_after:
            if agent.resource_type == "batch":
                return await execute_batch_pr_creation(session, agent)
            return await execute_pr_creation(session, agent)

        if changes:
            summary = "\n".join(f"- {c}" for c in changes)
            return build_response(
                f"Updated:\n{summary}\n\nSay **confirm** to continue.",
                resource_type=agent.resource_type,
                resource_status="pr_setup",
            )

    if action == "proceed":
        if agent.resource_type == "batch":
            return await execute_batch_pr_creation(session, agent)
        return await execute_pr_creation(session, agent)

    if action == "skip":
        return _handle_skip(session, agent)

    return build_response(
        message or "Say **confirm** to continue,"
        " or tell me what you would like to change.",
        resource_type=agent.resource_type,
        resource_status="pr_setup",
    )


# ================================================================
# PR EXECUTION
# ================================================================


async def execute_pr_creation(session, agent):
    rtype = agent.resource_type or "unknown"
    fields = agent.collected_fields or {}
    resource_name = (
        fields.get("bucket_name")
        or fields.get("database_name")
        or fields.get("role_name")
        or "unknown"
    )
    intake_id = fields.get("intake_id", "unknown")

    try:
        pr_result = await create_pr_for_resource(
            github_token=session.github_token,
            github_username=session.github_username or "unknown",
            resource_type=rtype,
            intake_id=intake_id,
            resource_name=resource_name,
            yaml_content=agent.generated_yaml,
            branch_name=agent.pr_branch_name,
            pr_title=agent.pr_title,
            pr_body=agent.pr_body,
            collected_fields=fields,
            upstream_branch=agent.pr_target_branch,
        )
    except Exception as e:
        pr_result = {"success": False, "error": str(e)}

    if pr_result and pr_result.get("success"):
        agent.phase = "done"
        agent._pr_url = pr_result["pr_url"]

        await _save_pr_record(
            session=session,
            pr_url=pr_result["pr_url"],
            branch_name=pr_result.get("branch_name", agent.pr_branch_name),
            target_branch=agent.pr_target_branch,
            title=pr_result.get("title", agent.pr_title),
            resource_types=[rtype],
            resource_count=1,
        )

        session.complete_current_resource()
        return build_response(
            f"**{rtype.upper()} - PR created successfully!**\n\n"
            f"- Branch: `{pr_result.get('branch_name', 'N/A')}`\n"
            f"- File: `{pr_result.get('file_path', 'N/A')}`\n"
            f"- PR: {pr_result['pr_url']}\n\n"
            f"Would you like to create another resource, or are we done?",
            resource_type=agent.resource_type,
            resource_status="confirmed",
            generated_yaml=agent.generated_yaml,
            pr_url=pr_result["pr_url"],
        )
    else:
        error_msg = (
            pr_result.get("error", "Unknown error") if pr_result else "Unknown error"
        )
        return build_response(
            f"PR creation failed: {error_msg}\n\n"
            f"You can:\n"
            f"  - **retry** - try again\n"
            f"  - **skip pr** - save without PR\n"
            f"  - **cancel** - discard",
            resource_type=agent.resource_type,
            resource_status="pr_setup",
            generated_yaml=agent.generated_yaml,
        )


async def execute_batch_pr_creation(session, agent):
    batch = session.batch
    if not batch:
        return build_response("No resources in batch.", resource_status="confirmed")

    count = len(batch)
    type_summary = agent.collected_fields.get("type_summary", f"{count} resources")

    resources = []
    for entry in batch:
        r = {
            "resource_type": entry["resource_type"],
            "intake_id": entry["intake_id"],
            "resource_name": entry["resource_name"],
            "yaml_content": entry["yaml"],
        }
        try:
            from app.services.path_resolver import resolve_file_path

            r["resolved_path"] = resolve_file_path(
                entry["resource_type"], entry.get("fields", {})
            )
        except Exception:
            pass
        resources.append(r)

    pr_title = agent.pr_title or f"[CONFIG] Batch - {type_summary}"
    pr_body = agent.pr_body

    if not pr_body:
        body_lines = ["## Infrastructure Configuration Batch\n"]
        for i, entry in enumerate(batch, 1):
            body_lines.append(
                f"### {i}. {entry['resource_type'].upper()} - {entry['resource_name']}"
            )
            body_lines.append(f"**Intake ID:** {entry['intake_id']}")
            body_lines.append(f"```yaml\n{entry['yaml']}\n```\n")
        body_lines.append(
            "---\n_This PR was automatically generated by PR Chatbot._"
        )
        pr_body = "\n".join(body_lines)

    try:
        pr_result = await create_pr_for_batch(
            github_token=session.github_token,
            github_username=session.github_username or "unknown",
            resources=resources,
            branch_name=agent.pr_branch_name,
            pr_title=pr_title,
            pr_body=pr_body,
            upstream_branch=agent.pr_target_branch,
        )
    except Exception as e:
        pr_result = {"success": False, "error": str(e)}

    if pr_result and pr_result.get("success"):
        batch_types = list(set(e["resource_type"] for e in batch))
        await _save_pr_record(
            session=session,
            pr_url=pr_result["pr_url"],
            branch_name=pr_result.get("branch_name", agent.pr_branch_name),
            target_branch=agent.pr_target_branch,
            title=pr_result.get("title", pr_title),
            resource_types=batch_types,
            resource_count=count,
        )

        for entry in batch:
            entry["pr_url"] = pr_result["pr_url"]
            session.completed_resources.append(entry)
        session.clear_batch()
        session.current_agent = None

        file_count = len(pr_result.get("file_paths", resources))
        return build_response(
            f"**PR created with {count} resources!**\n\n"
            f"- Branch: `{pr_result.get('branch_name', 'N/A')}`\n"
            f"- Files: {file_count}\n"
            f"- PR: {pr_result['pr_url']}\n\n"
            f"Would you like to create more resources, or are we done?",
            resource_status="confirmed",
            pr_url=pr_result["pr_url"],
        )
    else:
        error_msg = (
            pr_result.get("error", "Unknown error") if pr_result else "Unknown error"
        )
        return build_response(
            f"PR creation failed: {error_msg}\n\n"
            f"You can:\n"
            f"  - **retry** - try again\n"
            f"  - **skip pr** - save without PR\n"
            f"  - **cancel** - discard",
            resource_status="pr_setup",
        )


# ================================================================
# RESUME - called from generator_agent after an interrupted
#          resource flow completes or is cancelled
# ================================================================


def resume_pr_from_pause(session):
    paused = session.paused_pr_state
    if not paused:
        return None

    agent = session.start_new_resource()
    agent.resource_type = paused["resource_type"]
    agent.phase = "pr_setup"
    agent.pr_sub_phase = paused["pr_sub_phase"]
    agent.pr_branch_name = paused["pr_branch_name"]
    agent.pr_title = paused["pr_title"]
    agent.pr_body = paused["pr_body"]
    agent.pr_target_branch = paused["pr_target_branch"]
    agent.available_branches = paused["available_branches"]
    agent.fork_exists = paused["fork_exists"]
    agent.fork_full_name = paused["fork_full_name"]
    agent.collected_fields = paused["collected_fields"]
    agent.generated_yaml = paused["generated_yaml"]

    session.paused_pr_state = None

    is_batch = agent.resource_type == "batch"
    batch = session.batch

    if is_batch and batch:
        from collections import Counter

        count = len(batch)
        type_counts = Counter(e["resource_type"].upper() for e in batch)
        type_summary = ", ".join(f"{v} {k}" for k, v in type_counts.items())
        agent.pr_title = f"[CONFIG] Batch - {type_summary}"
        agent.collected_fields["batch_count"] = count
        agent.collected_fields["type_summary"] = type_summary
        body_lines = [
            f"## Infrastructure Configuration Batch ({count} resources)\n"
        ]
        for i, entry in enumerate(batch, 1):
            body_lines.append(
                f"### {i}. {entry['resource_type'].upper()} - {entry['resource_name']}"
            )
            body_lines.append(f"**Intake ID:** {entry['intake_id']}")
            body_lines.append(f"```yaml\n{entry['yaml']}\n```\n")
        body_lines.append(
            "---\n_This PR was automatically generated by PR Chatbot._"
        )
        agent.pr_body = "\n".join(body_lines)
        agent.generated_yaml = "\n---\n".join(e["yaml"] for e in batch)

    batch_count = len(batch) if batch else 0

    if is_batch:
        agent.pr_sub_phase = "show_files"
        msg = (
            f"**PR setup resumed!** Your batch now has"
            f" {batch_count} resource(s).\n\n"
            f"Target branch: `{agent.pr_target_branch}`"
            f" | Title: **{agent.pr_title}**\n\n"
        )
        files_response = _present_files(session, agent)
        files_response["message"] = msg + files_response["message"]
        return files_response
    else:
        sub = agent.pr_sub_phase
        msg = "**PR setup resumed** (continuing from where you left off).\n\n"

        if sub == "ask_branch":
            branch_list = "\n".join(
                f"  - `{b}`" for b in (agent.available_branches or [])[:10]
            )
            return build_response(
                msg + f"Which branch should this PR target?\n{branch_list}"
                f"\n\n**confirm** to use `{agent.pr_target_branch}`.",
                resource_type=agent.resource_type,
                resource_status="pr_setup",
            )
        elif sub == "ask_title":
            return build_response(
                msg + f"Current title: **{agent.pr_title}**\n\n"
                f"**confirm** to keep, or type `title: New Title` to change.",
                resource_type=agent.resource_type,
                resource_status="pr_setup",
            )
        elif sub == "show_files":
            files_response = _present_files(session, agent)
            files_response["message"] = msg + files_response["message"]
            return files_response
        elif sub == "confirm":
            summary = _present_final_summary(session, agent)
            summary["message"] = msg + summary["message"]
            return summary
        else:
            return build_response(
                msg + "Say **confirm** to continue or **cancel** to abort.",
                resource_type=agent.resource_type,
                resource_status="pr_setup",
            )
